apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: devops-alerts
  namespace: default
  labels:
    release: monitoring

spec:
  groups:
  - name: devops.rules
    rules:

    - alert: HighCPUUsage
      expr: sum(rate(container_cpu_usage_seconds_total[1m])) > 0.5
      for: 1m
      labels:
        severity: warning

      annotations:
        summary: "High CPU usage detected"
        description: "CPU usage is above 50% for more than 1 minute"
